### ISSUE TITLE
with instructions, having problems connecting to docker-machine

### ISSUE THREAD

**Issue by aspyker** [AdityaGupta1/mobycraft#65]
Are you configuring your docker-machine to not use TLS?  With default docker-machine I get:

Caused by: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
    at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:98) ~[httpclient-4.3.3.jar:4.3.3]
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314) ~[httpclient-4.3.3.jar:4.3.3]
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363) ~[httpclient-4.3.3.jar:4.3.3]
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219) ~[httpclient-4.3.3.jar:4.3.3]
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195) ~[httpclient-4.3.3.jar:4.3.3]
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86) ~[httpclient-4.3.3.jar:4.3.3]
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.3.jar:4.3.3]
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.3.3.jar:4.3.3]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.3.3.jar:4.3.3]
    at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:441) ~[ApacheConnector.class:?]
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246) ~[ClientRuntime.class:?]
    at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:705) ~[JerseyInvocation$3.class:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[Errors.class:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[Errors.class:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[Errors.class:?]
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424) ~[RequestScope.class:?]
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:701) ~[JerseyInvocation.class:?]
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:417) ~[JerseyInvocation$Builder.class:?]
    at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:313) ~[JerseyInvocation$Builder.class:?]
    at com.github.dockerjava.jaxrs.ListContainersCmdExec.execute(ListContainersCmdExec.java:42) ~[ListContainersCmdExec.class:?]
    at com.github.dockerjava.jaxrs.ListContainersCmdExec.execute(ListContainersCmdExec.java:16) ~[ListContainersCmdExec.class:?]
    at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23) ~[AbstrSyncDockerCmdExec.class:?]
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33) ~[AbstrDockerCmd.class:?]
    at org.redfrog404.mobycraft.commands.dockerjava.ContainerListCommands.getAll(ContainerListCommands.java:108) ~[ContainerListCommands.class:?]
    at org.redfrog404.mobycraft.commands.dockerjava.MainCommand.updateContainers(MainCommand.java:521) ~[MainCommand.class:?]
    at org.redfrog404.mobycraft.commands.dockerjava.MainCommand.onTick(MainCommand.java:512) ~[MainCommand.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_MainCommand_onTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:352) ~[FMLCommonHandler.class:?]
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:248) ~[EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:366) ~[EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:347) ~[NetHandlerPlayServer.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:36) ~[C03PacketPlayer.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:10) ~[C03PacketPlayer.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_73]
    at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
    ... 5 more

**Comment by AdityaGupta1** [comment]
This error usually shows up when docker host or docker cert path is incorrect. Have you set the docker host or cert path yet? 

You can use `/docker host <host>` and `/docker path <path>` in-game to set the host and path, respectively. You can also look at the config file (`<your forge directory>/run/config/mobycraft/mobycraft.txt`) to see what values mobycraft is using. If no values are set, mobycraft will use default values of `192.168.99.100:2376` for the host and `<your home directory>/.docker/machine/machines/default` for path.

**Comment by aspyker** [comment]
The problem was that I was specifying the host as tcp://ip:port.  It seems like you need to specify ip:port and tcp is prepended?

**Comment by AdityaGupta1** [comment]
Docker-java only takes `https://` host values, so I added some code that converts `tcp` tp `https`. It should work now.
